# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sliki' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sliki

  # Pods for Bars
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'ObjectMapper', '~> 3.4'
  pod 'GoogleMaps'
  pod 'R.swift'
  pod 'SnapKit', '~> 5.0.0'
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'SVProgressHUD'

  target 'slikiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'slikiUITests' do
    # Pods for testing
  end

end
